apiVersion: v1
kind: NodePort
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30001